name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:

  build:
    name: Build
    runs-on: "ubuntu-26.04"
    steps:

    - name: Set up Go
      uses: actions/setup-go@v6.5.0
      with:
        go-version: '1.26'
      id: go

    - name: Check out code
      uses: actions/checkout@v7

    - name: Build
      run: CGO_ENABLED=0 go build -o process-output-mcp ./cmd/process-output-mcp

    - name: Test
      run: go test ./...